import './globals.css'

import type { Metadata } from 'next'
import { Open_Sans as openSans } from 'next/font/google'

import Header from '@/components/Header'

const fontFamily = openSans({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Multi Step Form',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang='en'>
            <body className={fontFamily.className}>
                <Header />
                {children}
            </body>
        </html>
    )
}
